### ISSUE TITLE
Closing elements correctly

### ISSUE THREAD

**Issue by aubreywullschleger** [kellyclaus/prj-rev-bwfs-dasmoto#2]
Subtlety for errors!  Line 17 in your `index.html` file, make sure you are closing your `<span>` element correctly.  Here you are using `</class>` instead of `</span>`

https://github.com/kellyclaus/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/index.html#L17

**Comment by kellyclaus** [comment]
Ha oops. Thanks - surprised it worked!
