### ISSUE TITLE
Alt attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [kellyclaus/prj-rev-bwfs-dasmoto#3]
Subtlety for errors!  Be sure to use descriptive `alt` attributes on your `<img>` elements like this:  `<img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg" alt="hacksaw paint brushes">` as this is best practice and makes your site more accessible.

Example: https://github.com/kellyclaus/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/index.html#L13

**Comment by kellyclaus** [comment]
Yup I always forget those. Thanks for the reminder!
